version: '3'
services:
   mysql:
     image: mysql
     command: --default-authentication-plugin=mysql_native_password
     volumes:
       - ./itrq.sql:/docker-entrypoint-initdb.d/itrq.sql    
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: itrq
       MYSQL_DATABASE: itrq_db
       MYSQL_USER: itrq
       MYSQL_PASSWORD: itrq
   web:
     depends_on:
       - mysql
     build: .
     ports:
       - "80:3000"
     restart: always
     environment:
       DB_PORT: 3306
       DB_HOST: mysql
       DB_USER: itrq
       DB_PASSWORD: itrq
       DB_DATABASE: itrq_db
volumes:
    db_data: {}